export const GAME_FIRST_SELECTION = "GAME_FIRST_SELECTION"
export const GAME_SECOND_SELECTION = "GAME_SECOND_SELECTION"
export const GAME_RESET_SELECTION = "GAME_RESET_SELECTION"
export const GAME_COMMIT_MOVE = "GAME_COMMIT_MOVE"